### ISSUE TITLE
detailed usage of adding monitors and listing monitors

### ISSUE THREAD

**Issue by boshnak** [lucasheld/uptime-kuma-api#10]
Hi,
awesome tool. can we get some more example of how to add new monitors and list existing monitors?

currently we are getting the following error when trying to add a monitor.

>>> api.add_monitor(type=MonitorType.HTTP, name="Test API", url="https://gm.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xx/python-venvs/uptime/lib/python3.6/site-packages/uptime_kuma_api/api.py", line 637, in add_monitor
    return self._call('add', data)
  File "/home/xx/python-venvs/uptime/lib/python3.6/site-packages/uptime_kuma_api/api.py", line 340, in _call
    r = self.sio.call(event, data)
  File "/home/xx/python-venvs/uptime/lib/python3.6/site-packages/socketio/client.py", line 469, in call
    callback=event_callback)
  File "/home/xx/python-venvs/uptime/lib/python3.6/site-packages/socketio/client.py", line 394, in emit
    namespace + ' is not a connected namespace.')
socketio.exceptions.BadNamespaceError: / is not a connected namespace.

**Comment by lucasheld** [comment]
I'm not sure how this error occurred. It looks like the login was successful, but when the monitor was created uptime kuma was no longer reachable.

This is an example code that works with a fresh uptime kuma instance.

```python
from uptime_kuma_api import UptimeKumaApi, MonitorType

username = "admin"
password = "secret123"

api = UptimeKumaApi("http://127.0.0.1:3001/")
if api.need_setup():
    api.setup(username, password)
api.login(username, password)

r = api.add_monitor(type=MonitorType.HTTP, name="Test API", url="https://gm.com")
print(r)
# {'msg': 'Added Successfully.', 'monitorID': 1}

monitors = api.get_monitors()
print(monitors)
# [{'id': 1, 'name': 'Test API', 'url': 'https://gm.com', 'method': 'GET', 'hostname': None, 'port': 53, 'maxretries': 0, 'weight': 2000, 'active': True, 'type': 'http', 'interval': 60, 'retryInterval': 60, 'resendInterval': 0, 'keyword': None, 'expiryNotification': False, 'ignoreTls': False, 'upsideDown': False, 'maxredirects': 10, 'accepted_statuscodes': ['200-299'], 'dns_resolve_type': 'A', 'dns_resolve_server': '1.1.1.1', 'dns_last_result': None, 'pushToken': None, 'docker_container': None, 'docker_host': None, 'proxyId': None, 'notificationIDList': [], 'tags': [], 'mqttUsername': None, 'mqttPassword': None, 'mqttTopic': None, 'mqttSuccessMessage': None, 'databaseConnectionString': None, 'databaseQuery': None, 'authMethod': '', 'authWorkstation': None, 'authDomain': None, 'radiusUsername': None, 'radiusPassword': None, 'radiusCalledStationId': None, 'radiusCallingStationId': None, 'radiusSecret': None, 'headers': None, 'body': None, 'basic_auth_user': None, 'basic_auth_pass': None}]

api.disconnect()
```

**Comment by boshnak** [comment]
looks like its related to the python version I used (3.6.9)
once I switch to 3.7.5 it worked as expected.

any chance to get more examples of the api? how to edit existing monitors, which inputs are supported while creating a monitor, e.g. retry count before notificiation, etc.

**Comment by lucasheld** [comment]
Supported parameters for `add_monitor` and `edit_monitor`:
https://github.com/lucasheld/uptime-kuma-api/blob/dac368e2a5bd67c1c5dd24dc6ae29bb64e808651/uptime_kuma_api/api.py#L445-L502

An existing monitor can be edited by passing the id of the monitor and the key-value pairs of monitor parameters that should be edited.
https://github.com/lucasheld/uptime-kuma-api/blob/dac368e2a5bd67c1c5dd24dc6ae29bb64e808651/uptime_kuma_api/api.py#L639

Example:
```python
# add a new monitor
r = api.add_monitor(type=MonitorType.HTTP, name="Test API", url="https://gm.com")
print(r)
# {'msg': 'Added Successfully.', 'monitorID': 1}

# save the id of the new monitor
monitor_id = r["monitorID"]

# get and print the monitor
monitor = api.get_monitor(monitor_id)
print(monitor)
# {'id': 1, 'name': 'Test API', 'url': 'https://gm.com', 'method': 'GET', 'hostname': None, 'port': 53, 'maxretries': 0, 'weight': 2000, 'active': True, 'type': 'http', 'interval': 60, 'retryInterval': 60, 'resendInterval': 0, 'keyword': None, 'expiryNotification': False, 'ignoreTls': False, 'upsideDown': False, 'maxredirects': 10, 'accepted_statuscodes': ['200-299'], 'dns_resolve_type': 'A', 'dns_resolve_server': '1.1.1.1', 'dns_last_result': None, 'pushToken': None, 'docker_container': None, 'docker_host': None, 'proxyId': None, 'notificationIDList': [], 'tags': [], 'mqttUsername': None, 'mqttPassword': None, 'mqttTopic': None, 'mqttSuccessMessage': None, 'databaseConnectionString': None, 'databaseQuery': None, 'authMethod': '', 'authWorkstation': None, 'authDomain': None, 'radiusUsername': None, 'radiusPassword': None, 'radiusCalledStationId': None, 'radiusCallingStationId': None, 'radiusSecret': None, 'headers': None, 'body': None, 'basic_auth_user': None, 'basic_auth_pass': None}

# edit the monitor, change the url and the heartbeat interval
r = api.edit_monitor(monitor_id, url="https://google.com", interval=20)
print(r)
# {'msg': 'Saved.', 'monitorID': 1}

# get and print the monitor again
monitor = api.get_monitor(monitor_id)
print(monitor)
# {'id': 1, 'name': 'Test API', 'url': 'https://google.com', 'method': 'GET', 'hostname': None, 'port': 53, 'maxretries': 0, 'weight': 2000, 'active': True, 'type': 'http', 'interval': 20, 'retryInterval': 60, 'resendInterval': 0, 'keyword': None, 'expiryNotification': False, 'ignoreTls': False, 'upsideDown': False, 'maxredirects': 10, 'accepted_statuscodes': ['200-299'], 'dns_resolve_type': 'A', 'dns_resolve_server': '1.1.1.1', 'dns_last_result': None, 'pushToken': None, 'docker_container': None, 'docker_host': None, 'proxyId': None, 'notificationIDList': [], 'tags': [], 'mqttUsername': None, 'mqttPassword': None, 'mqttTopic': None, 'mqttSuccessMessage': None, 'databaseConnectionString': None, 'databaseQuery': None, 'authMethod': '', 'authWorkstation': None, 'authDomain': None, 'radiusUsername': None, 'radiusPassword': None, 'radiusCalledStationId': None, 'radiusCallingStationId': None, 'radiusSecret': None, 'headers': None, 'body': None, 'basic_auth_user': None, 'basic_auth_pass': None}
```

**Comment by lucasheld** [comment]
I have started writing documentation for this module, with examples for all methods. I will publish it the next days.

**Comment by boshnak** [comment]
thank you!!

**Comment by lucasheld** [comment]
The documentation is now available here: https://uptime-kuma-api.readthedocs.io/
