### ISSUE TITLE
allow 2.0.0-dev-nightly

### ISSUE THREAD

**Issue by mabed-fr** [lucasheld/uptime-kuma-api#74]
Hello,

can bypass version check ?

```
>>> api.add_monitor(
...     type=MonitorType.HTTP,
...     name="Google",
...     url="https://google.com"
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/share/virtualenvs/uptime-kuma-yMP0JEtU/lib/python3.11/site-packages/uptime_kuma_api/api.py", line 1468, in add_monitor
    data = self._build_monitor_data(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/uptime-kuma-yMP0JEtU/lib/python3.11/site-packages/uptime_kuma_api/api.py", line 813, in _build_monitor_data
    if parse_version(self.version) >= parse_version("1.22"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/uptime-kuma-yMP0JEtU/lib/python3.11/site-packages/packaging/version.py", line 56, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/uptime-kuma-yMP0JEtU/lib/python3.11/site-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '2.0.0-dev-nightly-20240624080807'
```

**Comment by lordofinsomnia** [comment]
+1
Any progress on this issue?

but my log in uptime kuma:
`uptime-kuma  | 2024-12-09T22:33:07+01:00 [MONITOR] ERROR: Error adding Monitor: undefined User ID: 1`

on api is:

```
/home/family/work/forever_wip/venv_3_11/bin/python /home/family/work/forever_wip/uptime_kuma.py 
Traceback (most recent call last):
  File "/home/family/work/forever_wip/uptime_kuma.py", line 31, in <module>
    api.add_monitor(type=MonitorType.HTTP, name="test", url='https://www.google.com/')
  File "/home/family/work/forever_wip/venv_3_11/lib/python3.11/site-packages/uptime_kuma_api/api.py", line 1472, in add_monitor
    return self._call('add', data)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/family/work/forever_wip/venv_3_11/lib/python3.11/site-packages/uptime_kuma_api/api.py", line 550, in _call
    raise UptimeKumaException(r.get("msg"))
uptime_kuma_api.exceptions.UptimeKumaException: insert into `monitor` (`accepted_statuscodes_json`, `auth_method`, `body`, `conditions`, `database_connection_string`, `description`, `dns_resolve_server`, `dns_resolve_type`, `expiry_notification`, `headers`, `hostname`, `http_body_encoding`, `ignore_tls`, `interval`, `kafka_producer_brokers`, `kafka_producer_sasl_options`, `maxredirects`, `maxretries`, `method`, `mqtt_password`, `mqtt_success_message`, `mqtt_topic`, `mqtt_username`, `name`, `packet_size`, `parent`, `port`, `proxy_id`, `rabbitmq_nodes`, `resend_interval`, `retry_interval`, `timeout`, `type`, `upside_down`, `url`, `user_id`) values ('["200-299"]', '', NULL, NULL, NULL, NULL, '1.1.1.1', 'A', false, NULL, NULL, 'json', false, 60, NULL, NULL, 10, 1, 'GET', '', '', '', '', 'test', 56, NULL, NULL, NULL, NULL, 0, 60, 48, 'http', false, 'https://www.google.com/', 1) - SQLITE_CONSTRAINT: NOT NULL constraint failed: monitor.conditions
```
